-- Criando a função
CREATE OR REPLACE FUNCTION OBTER_DESCRICAO_SEGMERCADO(
    P_ID SEGMERCADO.ID%TYPE
) RETURN SEGMERCADO.DESCRICAO%TYPE

IS
    V_DESCRICAO SEGMERCADO.DESCRICAO%TYPE;
BEGIN

    SELECT DESCRICAO INTO V_DESCRICAO
    FROM SEGMERCADO
    WHERE ID = P_ID;
    
    RETURN V_DESCRICAO;
END;

-- Formas de executar a função
-- Opção 1
VARIABLE G_DESCRICAO VARCHAR2(100)
EXECUTE :G_DESCRICAO := OBTER_DESCRICAO_SEGMERCADO(1)
PRINT G_DESCRICAO

-- Opção 2
SET SERVEROUTPUT ON;
  DECLARE V_DESCRICAO SEGMERCADO.DESCRICAO%TYPE;
  
BEGIN
  V_DESCRICAO := OBTER_DESCRICAO_SEGMERCADO(2);
  DBMS_OUTPUT.PUT_LINE('Descricao: ' || V_DESCRICAO);
END;


-- Procudure para incluir cliente
CREATE OR REPLACE PROCEDURE INCLUIR_CLIENTE(
    P_ID            IN CLIENTE.ID%TYPE,
    P_SEGMERCADO_ID IN CLIENTE.SEGMERCADO_ID%TYPE,
    P_RAZAO_SOCIAL  IN CLIENTE.RAZAO_SOCIAL%TYPE,
    P_CNPJ          IN CLIENTE.CNPJ%TYPE,
    P_FATURAMENTO   IN CLIENTE.FATURAMENTO_PREVISTO%TYPE
)
IS 
    --variaveis de trabalho
    V_CATEGORIA CLIENTE.CATEGORIA%TYPE;
BEGIN

    IF P_FATURAMENTO < 10000 THEN
        V_CATEGORIA := 'PEQUENO';
        ELSIF P_FATURAMENTO < 50000 THEN
            V_CATEGORIA := 'MEDIO';
        ELSIF P_FATURAMENTO < 100000 THEN
            V_CATEGORIA := 'MEDIO GRANDE';
        ELSE
        V_CATEGORIA := 'GRANDE';
        END IF;
        
    INSERT INTO CLIENTE VALUES 
    (P_ID, P_SEGMERCADO_ID, UPPER(P_RAZAO_SOCIAL), P_CNPJ, SYSDATE, P_FATURAMENTO, V_CATEGORIA);
    
END;

-- Executa Procedure
EXECUTE INCLUIR_CLIENTE(1, NULL, 'SUPERMERCADO XYZ', '12345', 150000)
-- Confirma inclusão do cliente
SELECT * FROM CLIENTE

--- função categoria_cliente
CREATE OR REPLACE FUNCTION CATEGORIA_CLIENTE(
    P_FATURAMENTO IN CLIENTE.FATURAMENTO_PREVISTO%TYPE
    ) RETURN CLIENTE.CATEGORIA%TYPE
IS
BEGIN
    
    IF P_FATURAMENTO < 10000 THEN
       RETURN 'PEQUENO';
        ELSIF P_FATURAMENTO < 50000 THEN
            RETURN 'MEDIO';
        ELSIF P_FATURAMENTO < 100000 THEN
            RETURN 'MEDIO GRANDE';
        ELSE
            RETURN'GRANDE';
        END IF;
END;

--- Procedure otimizada
CREATE OR REPLACE PROCEDURE INCLUIR_CLIENTE(
    P_ID            IN CLIENTE.ID%TYPE,
    P_SEGMERCADO_ID IN CLIENTE.SEGMERCADO_ID%TYPE,
    P_RAZAO_SOCIAL  IN CLIENTE.RAZAO_SOCIAL%TYPE,
    P_CNPJ          IN CLIENTE.CNPJ%TYPE,
    P_FATURAMENTO   IN CLIENTE.FATURAMENTO_PREVISTO%TYPE
)
IS 
    --variavel de trabalho
    V_CATEGORIA CLIENTE.CATEGORIA%TYPE;
BEGIN
    
    -- apropria na variavel v_categoria a categoria retornada na função categoria_cliente
    V_CATEGORIA := CATEGORIA_CLIENTE(P_FATURAMENTO);
        
    INSERT INTO CLIENTE VALUES 
    (P_ID, P_SEGMERCADO_ID, UPPER(P_RAZAO_SOCIAL), P_CNPJ, SYSDATE, P_FATURAMENTO, V_CATEGORIA);
    
END;
