-- parametro out
CREATE OR REPLACE PROCEDURE FORMATA_CNPJ(
    P_CNPJ IN OUT CLIENTE.CNPJ%TYPE
)
IS
BEGIN
    P_CNPJ := SUBSTR(P_CNPJ,1,2) || '/' || SUBSTR(P_CNPJ,3);
END;

-- Testando a formatação
VARIABLE G_CNPJ VARCHAR2(10)
EXECUTE :G_CNPJ := '12345'
PRINT G_CNPJ

EXECUTE FORMATA_CNPJ(:G_CNPJ);
PRINT G_CNPJ;

-- Procedure inclui clientes otimizada
CREATE OR REPLACE PROCEDURE INCLUIR_CLIENTE(
    P_ID            IN CLIENTE.ID%TYPE,
    P_SEGMERCADO_ID IN CLIENTE.SEGMERCADO_ID%TYPE,
    P_RAZAO_SOCIAL  IN CLIENTE.RAZAO_SOCIAL%TYPE,
    P_CNPJ          IN CLIENTE.CNPJ%TYPE,
    P_FATURAMENTO   IN CLIENTE.FATURAMENTO_PREVISTO%TYPE
)
IS 
    --variavel de trabalho
    V_CATEGORIA CLIENTE.CATEGORIA%TYPE;
    V_CNPJ      CLIENTE.CNPJ%TYPE := P_CNPJ;
BEGIN
    
    -- apropria na variavel v_categoria a categoria retornada na função categoria_cliente
    V_CATEGORIA := CATEGORIA_CLIENTE(P_FATURAMENTO);
    
     FORMATA_CNPJ(V_CNPJ);
        
    INSERT INTO CLIENTE VALUES 
    (P_ID, P_SEGMERCADO_ID, UPPER(P_RAZAO_SOCIAL), V_CNPJ, SYSDATE, P_FATURAMENTO, V_CATEGORIA);
    
END;

-- incluir novo cliente
EXECUTE INCLUIR_CLIENTE(3, NULL, 'Industria RTY', '12378', 110000)
-- confirmar inclusão
SELECT * FROM CLIENTE
\